### Vectorization with Python

- Vectorization is the way of getting rid of explicit `for` loops in your code.
- It is a way of expressing operations as occurring on entire arrays rather than their individual elements.
- Vectorization is usually implemented through numpy arrays.

In [1]:
# example to showcase the comparison between vectorized and non-vectorized 

import numpy as np
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print("Vectorized version: " + str(1000*(toc-tic)) + "ms")

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()

print("Non-vectorized version: " + str(1000*(toc-tic)) + "ms")

Vectorized version: 0.0ms
Non-vectorized version: 299.97849464416504ms


### Python/Numpy Vectors

In [5]:
print("Rank 1 Array: (Neither a row vector nor a column vector)")
a = np.random.rand(5)
print(a)
print(a.shape)
print(a.T)
print(np.dot(a,a.T))

print()

print("An Actual Column Vector")
a = np.random.rand(5,1)
print(a,"\n")
print(a.shape,"\n")
print(a.T)
print(np.dot(a,a.T))

Rank 1 Array: (Neither a row vector nor a column vector)
[0.79400507 0.43522635 0.9666025  0.9873913  0.45357311]
(5,)
[0.79400507 0.43522635 0.9666025  0.9873913  0.45357311]
2.9348565510211895

An Actual Column Vector
[[0.06510562]
 [0.45571481]
 [0.07626836]
 [0.04181816]
 [0.01263552]] 

(5, 1) 

[[0.06510562 0.45571481 0.07626836 0.04181816 0.01263552]]
[[4.23874135e-03 2.96695936e-02 4.96549888e-03 2.72259733e-03
  8.22643315e-04]
 [2.96695936e-02 2.07675985e-01 3.47566227e-02 1.90571563e-02
  5.75819349e-03]
 [4.96549888e-03 3.47566227e-02 5.81686334e-03 3.18940292e-03
  9.63690429e-04]
 [2.72259733e-03 1.90571563e-02 3.18940292e-03 1.74875880e-03
  5.28394236e-04]
 [8.22643315e-04 5.75819349e-03 9.63690429e-04 5.28394236e-04
  1.59656362e-04]]
